spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  datasource:
    url: jdbc:hsqldb:file:database/testdb
    username: alert
    password: alert

  main:
    web-application-type: none